apiBaseUrl=http://{REPLACE_TO_CORRECT}:4111
apiVersion=/api/v1

admin.username=admin
admin.password=admin

uiRemote=http://localhost:4444/wd/hub/
uiBaseUrl=http://{REPLACE_TO_CORRECT}:3000
browser=chrome
browserSize=1920x1080