name: Run tests

#trigger
on: [push, workflow_dispatch]

#Workflow definition
jobs:
  run-tests:
    name: Set up services and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository #download code to runner
        uses: actions/checkout@v4

      - name: Set up JDK #setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Maven repository # cache maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{runner.os}}--maven-${{ hashFiles('**/pom.xml')}}
          restore-keys:
            ${{ runner.os }}--maven-

      - name: Set up services # run docker compose
        run: cd infra/docker_compose && bash restart_docker.sh cd../..

      - name: Runt tests
        run: ./mvnw clean test -q
        env:
          APIBASEURL: http://localhost:4111
          UIBASEURL: http://frontend

      - name: Run swagger coverage # build swagger API coverage report
        if: always()
        run: .swagger-coverage-commandline/bin/swagger-coverage-commandline -s http://localhost:4111/v3/api-docs -i target/swagger-coverage-output

      - name: Load test report history # load previous test execution runs data from GH pages
        uses: actions/checkout@v2
        continue-on-error: true
        if: always()
        with:
          ref: gh-pages # branch for the GitHub Pages content
          path: gh-pages # an arbitrary name for a directory to which the previous data will be saved.

      - name: Build test report  # build allure report(including previous executions)
        uses: simple-elf/allure-report-action@v1.13
        if: always()
        with:
          gh_pages: gh-pages # the directory name to which the previous data was downloaded. Must be the same as the path value from
          allure_results: target/allure-results # path to the current test results directory. From allure properties
          allure_history: allure-history # name for directory to which the result will be saved

      - name: Build Swagger coverage report  # copy swagger API coverage report to allure history
        if: always()
        run: sudo cp swagger-coverage-report.html allure-history/${{ github.run_number }} # unique identifier for each execution

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Clean up services # shut down env
        if: always()
        run: cd infra/docker_compose && docker compose down

      - name: Setup JQ
        if: always()
        uses: dcarbone/install-jq-action@v3
        with:
          version: '1.8'
          force: 'true'

      - name: Check API coverage
        if: always()
        run: .github/workflows/check-coverage.sh


